#!/usr/bin/env python3 
from itertools import product
from collections import defaultdict
from sys import argv
from aoc import AocDay

class AocDay24(AocDay):

    def add(self,p1,p2):
        return (p1[0]+p2[0],p1[1]+p2[1])

    def setup(self,data):
        grid = defaultdict(int)
        self.deltas = {'e':(2,0),'w':(-2,0),'nw':(-1,1),'sw':(-1,-1),'ne':(1,1),'se':(1,-1)}
        for line in data.splitlines():
            dirs = []
            i = 0
            while i < len(line):
                ilen = 2 if line[i:i+2] in ('nw','sw','ne','se') else 1
                dirs.append(line[i:i+ilen])
                i += ilen

            pos = (0,0)
            for d in dirs:
                pos = self.add(pos,self.deltas[d])
            grid[pos] = 1 - grid[pos]
        return grid

    def run_silver(self,data):
        tiles = self.setup(data)
        return sum(tiles.values())

    def run_gold(self,data):
        tiles = self.setup(data)
        adjacent = self.deltas.values()

        for _ in range(100):
            changes = []
            black = [k for k,v in tiles.items() if v == 1]
            for pos in set([self.add(d,p) for d,p in product(adjacent,black)]) | set(black):
                black_adjacent = sum(tiles[self.add(pos,delta)] for delta in adjacent)
                flip = (black_adjacent == 0 or black_adjacent > 2) if tiles[pos] else (black_adjacent == 2)
                if flip: changes.append(pos)

            for c in changes:
                tiles[c] = 1 - tiles[c]

        return sum(tiles.values())

if __name__ == "__main__":

    silver_tests = ["""nwwswee""","""sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew"""]

    gold_tests = ["""sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew""",""""""]

    data = """seweswweswnwseeeesenwneseeseee
wwswwwnewnenwsweneswwwwwseww
eneneeesweeneneeeswnene
nenwswwsenenwnwnenenenenwnesenwnenenenenene
eneeenwneseneeseseseswsewswseswsenwe
eeneneenenwneseneesweneene
wwwwnenenwwwwwswsww
wnwnwenwnwnwnwnenwwwnwnwnwseswnwnenw
sewsweswnwnweswswnwswe
swenwnwnenwnwnweneeswsenwswneswneswsew
seswsweseswneswswneswnwsenwswsenwswsesenw
swsenesewswnenwnewseswseenwnweseseseew
senwseswseswnwswswswseseeseseseswswesw
eeeeneeenweneeeeneesweenewwne
sewnwnwnwnwnwnwnwswnwwnenwnwnwnwnwnwnwe
swenenwneenwwnwwenwwnwwenwseswswnwe
seswseseeseswnwswswse
nenenenwswnenenenenene
wnwseswwwnwwswwswswseswnewwswseww
seeswwnenewwnwswsenewwswwwswswsww
wnesewnwwnwnenwwewsewnwneeseseswwnw
nesewsesesesesesewsweseseseseewnwsw
swswswsewseeswswswswswneswswwsewsesenesw
nesewswwwswswwwwswswwsewnwswnesew
seseesweswnweeswseenwnenweenwwe
swswnweswnwswswswseswseswswswsesesww
nwenenwsenenwnwnenenwneneneneneneneswnesw
eenwewnwsesweesesenwnewnwnwsenesw
wswswswneseseseswse
nwnwnwnwnwenwnwnwwnwsenwnwnenwnwnenew
swsesesewseeseseseseneeseenwesesesese
neseneswsenewsesenwwwswswsenweswnee
swswnwwswsweswswswwswswwwneswwswsw
swswswnewwswswnesweswwswwswnwwwww
neeesewnwnenweswswnwswsenenenwsenwsene
nwnwswnwswenwwwnwwenweenwwnwnww
neswswnwswsenwwswswsweswseswsw
neweeneneseeweeeseeeneswnweene
swenwneswsewswneswwnwswnwswswswswswwe
nenwswneswnenwsenwnenwsew
nwnwnwnenwnwswwnwnwnwneswsenenwnenenwnwnw
wseswsewnewseswswnweseseneswswnenenwse
neeeeeswneneneneneneeneeswnwnwneee
eneswneenwnenwsewswseeeenwseseew
swswswsewseeswenwseenwseswswswseswnwswse
seseeseewseseeseswsesenenwseseseeenee
neswswswswswswnwwswswwswswsewswnesww
wsenenwneneneswnwnwnenenenwnenwnenenwnw
wnwsenesenwwswsewsweenwwwwwswsw
swnwneseswseswnwswsewseswswseswswsweeswsw
seswswswnwneswswwnwswseswnwseswswswenesw
nwnwnwnwnwsenwnwnwwenwnw
nweeeeeeeeeeeswseenewsewne
neneneneseneeesenewwnwenewneneswne
nwwnwnwnwnwnwnwwwwsenwewnw
nwswnenenwneneseneneseenwnwnwnenwne
seneneneneeeenwsenenwsweeneeenenene
wnwwnwwnwswwswwnwnwnenwwwnwnwne
swwenewswwweewswswwswnwswswnwsw
newneswsenenwsenenwswesenwnwnwnenwnenese
neneswneweneneneeneneeeeeneesenw
seweseswsewsenwesenenwsese
newewseneesweswseneswnenewwsenwe
nesenwsewnwnwseswnwswsenenwewwnwsene
nwnewwsenewwnesewwse
swswesweneneneswenwswnenenesenewnee
swnwseenwnewneneseewne
nwwwnwnwenwnwwnwnwnwnw
eseseneswneseswsesenwwwsewnesesesee
nenwnwnwnwnwnwnwnwnwnenenwnwnesewsenesw
nenenenenenwneneswswnenenwwnwneneneenw
seswseswneewneswwseseswseseswswseswswse
wsewneseeseseseseneswsesesenesese
sweswswwswswswswswswswwneesweeww
neswswnwswswswswwswswsweseeswswswewsw
nwneenesenwswenenesenwswnenenewsenene
eweeeeeneeseesenwesweeeeee
wseeenwnweeswnesweeneeenenwseee
esenwseseesenwwseeeeeeeseesee
wwwnewwwswwsewwwewnewwwnwwse
swswseswseswsenwswswnwseswseswesenwese
senwseseseseenwseeseseseseeseswsesese
wewnewwswnwwnewnwswswseewwsww
wswswswswswwswswnwweeswwwwwww
eeenweewenesweeeeeseee
swwswesewswsenewwneswwwswwneeww
nwnwnenenwseneseenenwnenwnenwnenwswnenw
swwswsweeswwswwswwswneswwwnesesesw
nwneswneneneneneenwneneswnenenenenwnenw
nwwwswsewesenwwsweneswnenwseswwsw
sesesesewseneseseseseseesewsewsesesene
nenwneeswswswsewswnwnwwswneswsenew
senenwnwswnwswesewswnwnwnwnweenwneneswse
esewweeeeesenwneeseesweeeene
newwseseeseeseseseseseenwewsesese
seneseeeswweeesewneseseewseene
swseeseseeseswsewnweneswnwenesewnwse
eweneeewesenwneeneenewenesesw
wswnwneseswswnenenenwenenenewneneenw
seeneswsesewseseswnesenwseswswnwsesese
seewesewewsenewneneneswsenwesese
senwnwnwsewnwnwnwswnewnwnwenwnenenwswnwnw
swnwnwnenwwwsenwnenwnwnwnwenwwesewnwnw
seswswneswswswswswswwswneseswswwswswswsw
neseneswnenwwnenenwnwwnesenwnenwnenene
nwseseswswwswsewseswenwnwweeswesese
seneswswswseenweewswnewswwswnwswswne
sesenwswneeenwswseswswneewnenwneswe
ewewwwwwswwnwswwwnwewwww
swnenewesewwwswwsewwnwswwnwnene
wswnwsenwnwswenwnwenwnweswwwneee
weenewswswewnwnweesewnwsweswwsw
eeseeeseeeweeeseneeee
wnwenwnwnwenwnwnwnwnwswweneneswswnee
seseseswsewnwsewseeesenwseseswesese
weweesweeneeneeseeeweeseee
swseneesweenwneswnenwneewwwswswsw
nesewwenesenenwneneeneneneese
esesenewnwnweseseweeeeeeeswsw
nwswwwneswswseeswswnwswswnewsenwswesw
weeeseeseseseesesewnesenweeese
sewsesewnesesesesewneseeenesenwesese
swsesesenesenwsesewseseswseswseseswswse
neswswswwswswswswwswswswswswsw
nwnwnwnwnwnenwnwnwnwsenwnewnenw
seneneenwnwnwneswnwnwnenwnwnwnwnwnwnenw
swnweeeeeeeesew
neseswwnweeeeswseeseeeseeeswene
eeneeeseeneeseeeeewneeenwsw
senwswseesesesesweeenwseee
wwwwswwwsewswswswnewwswneswwsew
eseeneseeseswwseeweeeeneeee
wwnewwwwwwswwswwwewwwnewsew
sewwneeeeeesweeswenesesweneee
nenwnwenwnwswnwnwwswnww
swswseneswswesesenwsesewseswsesesesesenw
seeseseenwweseseseneeseeeeseese
newnenwseswwnwwwwnw
swwnewewwwwwwwwsewwwnwwwnw
swwnwnwnwswenwnwneenw
wnwnwswnenwnwweswweseswwswwewsw
nwenwnwnenwswewswnwnwenwnwnwwnwnenw
esewseseseeeeneseseeeewsenesw
swwwswwnwwnwwweswswsewwswwnesw
senwswnenwnwneenwswnwnwneenwnwnwnenwnww
wwnwwwwwwnewewwwwwsenwswsww
nwnwnwnwnwsewnwnwnwnwnw
swnweseswseseswenwwseneseneswnweswswsw
enenenewseseneseeeneneeneenenwnwne
neneneewwenesenenenenwneneneneneene
neeeneeeneneweeeneee
neseeswswswnwswwswswwswswnwswwswswsw
wwwnenewwnweseseswsenewnwnwnwwse
swwwwsewswswswswswswswwsweneswsw
seneseeseswsesesesesewseseseswsenw
nwwwwnwnwwnwsenwwwwww
wwwwwswnewewseneseswnewswwseewnw
neswnweeswneewwneeeeeneneenenese
neneeneewewsesewnwseeene
seneneneenwnwnwnwnenwnwnenwnwnenwnwswwe
wswswwwseswneswwswwsw
nenwnwesewneneewwwseswwsw
wnewnwwwwwnwnwewwwwswewseww
seeeeseenwsenweswsesesesenwseseee
nenwwsenenwnwnenwnenwnenenesenwnwnwnwnw
wwnwsewwswnewwswewwwwwwsww
seseseeeeseesenwseseseseseese
nweseseseswenesesesesewseseseseseneese
nwswswswwswsweswwsweswswswswswneswsw
wwwsewwwsewwwwwnwwenewnww
nwwnwwwwnwwsesenenwnwwwnwnwwwnw
newnewsewswneenesenenenenenwnesenwe
wnwswswnwwenwnweenwnwewnw
newnenesweneseenenenee
nesweneneneneseewneweeweewswee
wwwwswwwwwwwewww
nwnwsweswwnwnewnwnwnwnenwswwnwneswnw
esenesewswswswswswseswseseswswsw
nwnenenwwnesenenesweneswnenenenesenene
swwewnwwnewwwweswnwsewwnwnenw
swwwneseweseswwswneneswneneseswswnesw
nenwwneneneswnenenenenwnenenenesenw
swswswswseswswnwswseswswsw
swswswsweseswswswwswswswswneswswwsww
neseswseswseswswneneswswsewwswneswswsw
swwswwswwwswnwwwwwwswesww
swswsesewnwswswswseseseswswswne
nwseswswswswswseswseswse
sesewwsesewseesenesenwwseseesesesee
swnwwswswswsweswswwswswswswswswsw
nwnenenwnwnwsenenwwnwsenwseewnwesenww
wwswnwwwwenwwwwwnwsenewewwne
wsenesenwwnesenesenww
eeeeeswnwseseeeseneswenwsewswsee
swwwewwwewwswwwswnw
eeneswnweeswseeenwseeswnwweseee
nenwnwswneenenenwwnenwswneneneneneeenwsw
seseseswneesewwsenwseseesese
newnenenenwneseneenewnenenenesenenenenw
nenwswweseeswsenwsenwsewneswseneswnw
eeneewsenweeeneesewee
nwwnwwsewnwwwwwnwnenwsenweww
neneneswnewnenwneneswnenenenenenenwnesene
seseeseseswseesesenwseseswswsesenwsww
seeswnenwswwnenesenenwnwnwnenenenenene
wneneneswnenenwnwwee
newswwwwsewnwseswneenwwseewnewne
swswwwwswneeswwweseswnew
swnwseeseeewesweneeswenwswwwne
eweseeeeeeeeeenweseeeeenw
wwnwwsenewwwwwwnwnewseswswwsew
neeseseeeesesesesesesesenwsewsesew
nwnenwnenenenenwnwnenenenenenwenenesesw
senenenwnenenenenenewneneneene
senwseswwseswswseseneswswswswsenwseee
nenwwnesenenwseswsenewnenwswnenese
nenwnwnwsenwnwnwwwnwnwwwwnwwnw
seseeswsenwneeeesewwsenesenenwsewse
eeseeesenwseesweeewenwsesesee
eswnwnwwsenwnwnwwnwwne
swswsesenwswseswswswesw
nwwnwwnwnwnwnwnwnwse
newsesenwnwsewsenenewwse
swnwnwwsenwnwnenenwnwnenwnw
swswwnewewwsesenewnwseswswswswswsw
eeeneseeeseseeseeeweseese
neneneneneneseswenweseneweenewnwene
nwnwwnwnwnwnwnwnwwnwnwnwnwnwesenwnenw
senenenewswseeenwswesweeneene
nwnwnwenwnwnwnewsenwnwnenwsenenenwnwwnw
nwswswswseswswnwswswseswesenwswswswseseswsw
senwwnesenwswseseswseseswenwswesesee
weeseeeeseenee
nwnenwnwswnwnwnwnweswnenwswsee
wwwnewwwnwewneswneswnwswwsenwnww
wseswneeseseswenwsesenwnenewse
seneenwswnewneneeeeneeeneneneenenwne
sweneweeseeeseeeneewseee
eswseseenwsesesesewseenenwswnwseeswse
swneswwnwwwwwwseswwswwswswwsene
sesenesewswsesenesesesesesesesesesesese
weneweswewseseeeeneeseeenee
seeseeseenesweseesweeeeswneenwe
weseewnweeeswseseeeswswnewsenene
nenesenenenwnwnenesenenenwnenwwnwnwnenesew
nwweeeeeeeeeeseeseee
neswnenenenwnenenenwnwnwnwnenwne
neneenweeeswwseeswswenweweswnenw
wnwnwnwswewnwwwnewwnewnwwsenwnw
seeswseseswnewnwsesesesesesesesenewnwse
wnewsewewwwnwnwweeswwwnwswnw
seeseeseeeeeeeeeeenwweneew
eeeeseenwsweesenwnweeesenwswee
swwswnwseswswswswswswsweneswswswswswsw
nwnenwwnwwnwenwnwnwsenwnwnwnwwnwnww
swnewneneenewnenwswnwsenewnwneesee
wwwwwsewwwwnwnewnwwnenwseswnw
swsewweweswwwswnwwewwnewwwe
wnwenwswswwwwwwwwwwswewwne
nenenenenenenenenenenesesenenwnenwwnenwe
nwnenwenwenwwnwsenwnwnwwsenwnwnwwnwnw
seswnwnenwenwseswwenesenewneswnwnwnene
enenenwswnwnwnwnenenesenwnwsenwwnwnwnw
swsewwsewseenwnwnewnwwwnwnwnewse
seseswnwswswswswwseswne
nwwnwsewnwnwnwnwnwnwnwnwnwenwnwswnwnwe
swnenenesesenenenenwnenenewnesewneenene
seswsewswseseswseswswswnewneseswseswse
nwsewsenwnwnwwnwnwwswnewnenwwsewwwnw
seeeeseneswnwneenenwnenwneesenwe
wwneeenewseeesesesesweeesesese
swwswswsewseswswneneewneeswnwsesewe
nwneswswswsweswseswswswswseswswswnewswsw
nwnwwsenwwnwnwnwnwwwwnwnwenwsenwww
neenwswnwneenwnwwnwnenwnwswnwswnwnwe
nwswnwnwnwwnwswnwnwnwnwswneewnwnwnwnwenw
swswneseswseeeeeeseseneseesenwsewe
neseesesesewseweeweeneswseeeene
swseeswsesewswswseseeswseswnwsenwswnese
swwswwswsewswwswnwswseswwnenwswsww
nwneewnwnwnwnwwnwnwnwnwseswwnenwnwnwse
nwnwenenwnwnwnwwwenenewneswe
eseeneeneneeseneweenweneeewsw
wswswswsewswswnewweswnewwwswwwsw
newnenenwenenenenwnene
swwnwwswwwswwwenwwwewwwswwsw
neneeneneswwneneenenwseneeneneneeenwne
newnwswsweswseseswnwnwswswswseseswnee
eneeneeneweneneneswnweneesenenene
sweeeswnwneeneneenweeeneesw
neswsenwesesesesweseseweseseeeese
nwseswnwnwswneneenwnwnwwwnenesenenwnenw
sweeeeseeneesweseesenwneesweee
wwswneesewnwseseeeeweswesewsww
sesweswswseeswswsenwswswswwseswneswsesww
swneneneeseneenewnew
sesewsesenwnwesesesewseeeseswsesesese
swseswseswswewswnenwswneenwnwneswne
neneneneneneneneswenenenenwsw
weswwnwwwnwwswswnwnwewweeenwnw
wnwwwwwnwwswwnwnwsewnwwnwwwewe
nwwswwswnwneswsewseeswseseswnewnenwnesw
nwnwnweswsenwsenwswnesenwwnwsenwswee
nwwneseswswweseswseswswnenewseswswnww
eeesweneenwneeeneneswesewneswneene
weeneswswewseeeeeeenwneee
nwnwnwenwnwnwnwwwnwsewsewwwnenwnw
neenenwwneneeswseneswnewnene
enwnwnwnwnwnwnwnwnwenwsenwnwwswnwnwnwnwnw
wnwswseseneseseseswsesesewsenweeseew
swnweswnesenesewseneseseseenweeseew
nwseeeseseeseesesenwswneseseweseesw
wwwswwswneswwwwweww
seswwenwseneewneeneeswneneeswnwnew
nwswseswwwneswswswswwnwseswswesweswsw
sewswwwwswswsenwsenewwwwwwnwsww
nenenenenenwswnenenenenenenene
seseneseseesenwswsewseswswseseseswseseese
swwnesewnwseneswnenesweeeneswewne
nwnwnwwwnwwnwwnwnwswewenwnwnwnwnw
nwnwnwswwnwwsesenwnwwnwsenwenweneswnwnw
seswseeswnwseseswseswseswseseswseseswnw
swswsweswswsenewneswswsenwwswswswswe
sweswswswwwswswwnewwswnewswswnesw
weseseswswseseswsese
wnwwnwwwwwwwewwnwnw
neseeeseeswnwwnesee
nenesewswnesenenenwwnwnenweseeswwenw
seseseneswwsewnwweeeewnesesesesese
seswnewnwsenwswseseswsenwseesesesesesesese
neneneswnenwnwnesenenenenwnenesenesenenene
swneswswnewsenesweswseswwseswswswswsesw
nwnwneswsweeeneeneeeneneesenwnenene
senwnwswnwnweswwnwsenwswnwnesenwswwee
eneseswenwneseswneesenwwneeweewwsw
seewswswswenwnwwwnwnwnwwnwnwwnwne
eneenwnewswnwnewsewseneeswnwenesww
nenesenenenenwnesesenesewnenwnenwwnenese
eenesewsweeeweseweeeseneseee
weneeseesenesesesesesesesewesesee
swswwswwwswwwswnwswwnesweswwneswwsw
neswneseneneewnenenwsenwnenewneneenew
neseeswsweswwseeneenenewwnenwene
eeeneeneeeeweeeeee
nwenwwwwnwwwwwwwnw
nwswnwnwnwnwwnwnwnwnwsenwsewenwnwnwnw
swseneneneswnenenwnenenwneneswnenenenee
nenwnenwsenwnwnwwnwnenwnene
eeneeeeneeeeeeenesw
esweeeweseeeneneeenwseeswnwswswne
nenenenwnesenwnenenwnenenenenene
swnwewswwswnwswwswswnesweswswswwse
wenwneneenesweeneneeeeseneenenwe
nwnewnwnwenwswswnwnenwsenwee
wswnwesenwwswswewneswwweweswwnenw
seweswneeswneswneneeneneneneenewnesee
nenwnwnewneeneeeesweneneswneneswne
nenwenenenenenesweneneneeenenewee
nesenwneneneneneneseneswnwnenenenwnewse
wnwwsesewsewwswwneswneswwnewswww
nwnwsenenwnwnwnwnwwwenenwwwwswwww
neeseeeseseeseeseeesw
neneneswnwneneseneswwneseeneewne
nwswsewwswswewwwwwwwwwnwswsw
swswseseneseesenesenwswsesesesese
eenwwseswwwswsweeswswswswswswsese
eswneswswswswswnewwswswswweswenwe
nwseseswseswswseseseseseswnwseseneswsesw
swseeswenwseeeeseseneseseeeesenee
seeseswwwsesewseseseseseeeenwesee
seswswseseseseseseseeswenwswswswnwsesenese
nwnwwnwsenwwnwnwnwwnwnwnw
nenwnwswnwnweswnwnwenenwneeneswnwnenw
neenewneneneneeneenenwewnesenenene
swswwwnwwnenwswsesewsewww
nwnwnwwneeswswnwesenwnwsewnwwenwnwsww
wsewwwnenwsewwwsewwnewnwwsww
neeneneesweswneeewsweneneenenwenee
nwnewneeneneeseswesewenwneswneewe
wswwnewswswswswneswswswwwswsw
nwwwneneswsenewnwneeeswsweneswenwe
wswswswwswnenewewswswswwnwswseswsewsw
newwnwnwnwnenwnweswnenwnenwnwsenenene
nenwnenenenenenenwwnweneswnenenwsesenew
sesenwnewnwnwnwswsweswnwswwwwsewsee
wnwnwsenwnwnwnwnwenenwseeswnenwswnwsesw
nwnwwnwnwnenwsenwnwswnwenwswnwwenwnw
eeeeseseseeeeeweseneweesee
eswesewenweneeneeseseeseeeee
enenewnenenenenesweswnewnesenenenenenene
swnweeenwnenwnwewneswnewwswwenw
sweswseeesweeeeneeseeeeeneesenw
wnwnwswnwnenwnwnwnwnwneswnweswnwnenenw
swswswswswswwswwnwswsweswswewswwsw
nwenwnewwnwswwnwnwesenwsesenewnwnwnw
wwswwwwwwwwsenw
swwnwsewwnewwnwswnwnewwnwnwnwne
eeeesenweeenenenenweeeeswe
enesweswswewswswseswnwswnw
eswseswnwsenwsewesenenewwwseesenwse
sesewwnewwnewwwewwwnwswnwwww
nenenewnenenenenesenenenenenenenene
nenwnenenwnenwnewnwnenesenenwneswnwnwswne
seseeswnwnwseswsesewseeseseesewesenw
swsenewsewswseneseseeeeseswnweenwse
eswwnwwwewwswne
sewseneewswswseswwseeseswewseswnw
wswwwwwsewwwwwwwwwnwsenew
wnwnenenwswwwwewswsewwwesenwe
wweewnwnwsesenwwewnwwwwwsww
neenwneneeswnwnwneseenesene
nenwsenewnwnenwneswnenenwenwwne
neeseneenwneseenwseenewneswneenesew
nwnwnewnwnwwneswenwnwnwwnwsenwsenwwnw
neneweneseneewwswwnwnwsenwnewnenesene
nwnwnwnwnwnwnwnwnwwswenewnwnwnwenwnesw
weseeneeneeeeseeesesenwnwswswese
senenesewnenenwnenenenewnenenenene
wnwsenwnwwsenwnewwnwenwwwnwnwnww
enwnwnwnwnwsweswnwsenwnwwneneswwnwe
eswnenenwneneweneneeneenenenenwswe
nesesewseswseseeseswsesenesesesesenese
swnwneswnenenwswesweeesweewnweenwsw
swnwnwswswswwseneewwneewswwswswsw
ewnwswnenwwwswnwsenwnwnwnwwwwwnewnw
seseseseseeeesenw
nwnwwnwswwenwwnwnwnwnwswnwnwnwenwnwnw
nenwnenenenesenwnwswnwneneswnwenenwneese
wnwwwwswwewewwwwswnewwwsww
nwswsewswwswneswswnewswwswseswnwww
neenewneneneswenwwnewnwnwnenwsesenw
seseesesesesesesesesweswwsenwsesesese
nwewnwswneseseseewsesenwseseseeseese
ewneeeeeeesweewenewse
wnwwwwwwwwnwnwwsenenwwwwenw
wseswswswswwnenenwwewenwswnew
nenwsenenwnwnwnwnwwnwnwnw
wneeneenenenwsesewnewwsenenwswswsw
eeeeenweeswewsweeeeeenwee
wenwseswseswswnwswswswswneswseswseee
nenenwnwwenwnwnwnwnwnwnwnw
wsewwwnwnewwwwwwwwsewwww
wwwwswnwwswwswewenwswwwwnwswwse
seneswwwwewnewwwwswwswwswwwe
nesewswneswswnwwwsewwwwswswwnesw
swewseswnwnwswweseeswwswnwnweswsw
nwnwnwenwnwswwsenewswnwnwnwnweenwnwsw
swenwswswseswswswswswswswswwswseseese
nwseswnwneswwswwnweeswewnwnwwwew
nwseswwnwenwewwnwnwswwnwnwnwnwseww
enweneeeeeeeenwsweesweew
nesenenwnwwwnwwswnwnwnwwnwwse
weneeeseseneeenweeeneneenwewe
senwnwnwnwswneneswnwnwnewnwsenwwnesee
nwneseneswnenenwnwnwwnw
wnwnwwswnwnwnwnwesewnwnwswnwnwwnwnenwe
nwswwswswwseewsweseswneeneseesew
enwwnwwswwswenwwsweenwnwewnwse
seewwwswnwwswwwwswswewwswswwnw
nenwnenwneenwsenenewnwwnenwnwnenwnw
swswseseswswswneswswswswswswsesweswsenwsene
neneneswswneneseneweswnenwseswseswwsw
wwweneswwwwwswsenew
swswswnwseswswswswswswswsw
nwnenesenenwnenwnwnwnw
eeesenwseeswseeeenwneswseeenwsenew
seeeeseseeswsesenweeeewsewsese
swseneswswseneswnwswswseseswseseswwsewsesw
nwswnenenwneenwsenwswnwnenenwnwnwsenenwsw
nwseseeeenwswswnwswese
nweneneenenwsenenenenese
wswswswwwwewwwneswwesewneswwswnw
nwsenwwnenwnenwsenewnwnwnesenenenwnwne
nenwswnwenwseswnenwwnwnwnwnwwenwnenenw
wseswweswenenwswwswseneewwwnew
seeswseseesewenenwswewe
swswwswswsenenwneswseswswswswswswswswsw
wnwsewsenenenwnwsewnwwenenwswnwnwsenw
seneeseeneswsesenweseswweeswsenwswe
nenenenwnwneenewesesenenenenewsenenene
eneeneeeeeeeeseenew"""

    answer = AocDay24(data,silver_tests,gold_tests,argv)

    print(answer)
